### ISSUE TITLE
Thanks, do you have a list of the services that are bloat ?

### ISSUE THREAD

**Issue by shodanx2** [PuPpY-ThEAuToMaTiOnIsT/windows_service_manager#1]
Hi,

thanks this script is something I soon will need, so great , thanks for posting on /r/windows10

I run a tiny windows 10 on a tiny chromebox 

I was wondering which services you're turning off ? 

I suppose there's a bunch of services that are useless for basically everything (windows search, the spyware)

And other that only make sense in certain context (windows defender, BITS)

So I would appreciate if you could post your tiered "services shit list" if you will !

**Comment by PuPpY-ThEAuToMaTiOnIsT** [comment]
Sure, here's a list of services that are often considered safe to disable in Windows, along with their full service name and the impact if they're disabled:

AdobeARMservice: Adobe Acrobat Update Service - If disabled, you won't receive updates for Adobe Acrobat.
AGSService: Adobe Genuine Software Integrity Service - If disabled, you won't be able to verify the authenticity of Adobe software.
BITS: Background Intelligent Transfer Service - If disabled, Windows updates won't be able to download in the background, potentially causing slower downloads.
DiagTrack: Connected User Experiences and Telemetry - If disabled, Windows won't be able to collect telemetry data, which could impact the accuracy of future updates.
dmwappushservice: Device Management Wireless Application Protocol - If disabled, Windows won't be able to connect to wireless devices.
edgeupdate: Microsoft Edge Update - If disabled, Microsoft Edge won't receive automatic updates.
edgeupdatem: Microsoft Edge Update (Manual) - If disabled, Microsoft Edge won't receive manual updates.
lfsvc: Geolocation Service - If disabled, Windows won't be able to determine your location for certain apps.
MicrosoftEdgeElevationService: Microsoft Edge Elevation Service - If disabled, Microsoft Edge may not function correctly.
NetTcpPortSharing: Net.Tcp Port Sharing Service - If disabled, certain apps that rely on this service won't work.
nlsX86cc: Nalpeiron Licensing Service - If disabled, certain licensed apps may not function correctly.
RemoteAccess: Routing and Remote Access - If disabled, you won't be able to connect to remote servers.
RemoteRegistry: Remote Registry - If disabled, you won't be able to make registry changes to remote computers.
shpamsvc: Shared Phone Service - If disabled, your PC won't be able to connect to your phone.
ssh-agent: OpenSSH Authentication Agent - If disabled, you won't be able to use SSH.
SwitchBoard: Adobe SwitchBoard - If disabled, Adobe apps may not function correctly.
SysMain: Superfetch - If disabled, your PC may run slower.
TabletInputService: Touch Keyboard and Handwriting Panel Service - If disabled, the touch keyboard and handwriting panel may not function correctly.
Themes: Themes - If disabled, Windows won't be able to change your desktop theme.
tzautoupdate: Auto Time Zone Updater - If disabled, your PC won't update the time zone automatically.
uhssvc: Universal Host Process Service - If disabled, certain apps may not function correctly.
WbioSrvc: Windows Biometric Service - If disabled, biometric authentication won't work.
WpnService: Windows Push Notifications Service - If disabled, certain apps won't receive push notifications.
WSearch: Windows Search - If disabled, searching for files on your PC may be slower.


The below script can help provided its run using admin elevation in powershell:

Set-ExecutionPolicy RemoteSigned -Force
$services = @(
#the array of services which you want to disable, change it into comma separated values 
#with service names in double quotes and place it here
"AdobeARMservice",
"AGSService",
"BITS",
"DiagTrack",
"dmwappushservice",
"edgeupdate",
"edgeupdatem",
"lfsvc",
"MicrosoftEdgeElevationService",
"NetTcpPortSharing",
"nlsX86cc",
"RemoteAccess",
"RemoteRegistry",
"shpamsvc",
"ssh-agent",
"SwitchBoard",
"SysMain",
"TabletInputService",
"Themes",
"tzautoupdate",
"uhssvc",
"WbioSrvc",
"WpnService",
"WSearch"
)

foreach ($serviceName in $services) {
    if ($serviceName.StartsWith("#")) {
        Write-Host "Ignoring commented service: $serviceName"
        continue
    }

    if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
        Write-Host "Service $serviceName exists. Disabling service..."
        REG ADD HKLM\SYSTEM\CurrentControlSet\Services\$serviceName /v Start /f /t REG_DWORD /d 4
		Stop-Service $serviceName -Force
        $process = Get-Process -Name $serviceName -ErrorAction SilentlyContinue
        if ($process) {
            Write-Host "Process with PID $($process.Id) exists. Killing process..."
            Stop-Process -Id $process.Id -Force
        }
        sc stop $serviceName
    } else {
        Write-Host "Service $serviceName does not exist."
    }
}
Set-ExecutionPolicy Restricted -Force



I hope this list helps you optimize your Windows 10 experience on your tiny chromebox! If you find this information useful, please feel free to share my Github project with your colleagues.

**Comment by PuPpY-ThEAuToMaTiOnIsT** [comment]
**Set-ExecutionPolicy Restricted -Force** --> this has to be run after you run the script for security reasons. Thanks!

**Comment by github-ffmpeg-installer** [comment]
Thank you, I appreciate it, this will save me a lot of time, I was about go investigate every single service to determine which I could live without, this list really kickstarts this process !
